config/routes.rb
Rails.application.routes.draw do
  resources :expenses
  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "categories#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :expenses

    default_scope { order(:title) }

    validates :image, :title, :presence => :true

    def to_s
        ActionController::Base.helpers.image_tag(image, size: 20) + " #{title}"
    end
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :category

  default_scope { order("date DESC") }

  validates :title, :category, :amount, :date, :presence => :true

  def to_s
    "#{title}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    private def redirect
        redirect_to '/'
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
    @expenses = Expense.all

    @totalExpenses = 0
    @expenses.each do |expense|
      @totalExpenses += expense.amount
    end
  end

  # GET /categories/1 or /categories/1.json
  def show
    redirect()
  end

  # GET /categories/new
  def new
    @category = Category.new
    redirect()
  end

  # GET /categories/1/edit
  def edit
    redirect()
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:image, :title)
    end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: %i[ show edit update destroy ]

  # GET /expenses or /expenses.json
  def index
    @expenses = Expense.all
    redirect()
  end

  # GET /expenses/1 or /expenses/1.json
  def show
    redirect()
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
  end

  # GET /expenses/1/edit
  def edit
  end

  # POST /expenses or /expenses.json
  def create
    @expense = Expense.new(expense_params)

    respond_to do |format|
      if @expense.save
        format.html { redirect_to @expense, notice: "Expense was successfully created." }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1 or /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to @expense, notice: "Expense was successfully updated." }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1 or /expenses/1.json
  def destroy
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to expenses_url, notice: "Expense was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def expense_params
      params.require(:expense).permit(:title, :category_id, :amount, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/application/_header.html.erb
<%
    image ||= nil
    small ||= nil
    large ||= nil
%>
 
<header>
    <% if request.path != '/categories' && request.path != '/' %>
        <%=link_to 'Back', '/', class:'position-absolute text-secondary btn-back header__btn-hover' %>
    <% end %>
    <div class="row py-5 bg-primary rounded-bottom">
        <div class="col-10 offset-1 d-flex flex-row justify-content-start align-items-center">
            <%= image_tag(image, class: 'image img-fluid') %>
            <div class="d-flex flex-column mx-3 animation-bottom">
                <p class="introduction__header text-secondary mb-0"><%= small %></p>
                <h1 class="text-secondary mb-0"><%= large %></h1>
            </div>
        </div>      
    </div>
</header>

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :image, as: :string, label: "Image", placeholder: 'hamburger.png', required: true, error: 'Error', autofocus: true %>
    <%= f.input :title, as: :string, label: "Title", placeholder: 'Restaurants & Bars', required: true, error: 'Error' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<%= render 'header',
            image: 'waving-hand.png',
            small: "Welcome back,",
            large: "John Doe!" %>

<div class="container">
  <div class="row offset-0 offset-lg-1">
    <div class="col-12 col-lg-5">
        
        <div class="overview__container bg-secondary py-5 px-5 rounded">
          <div class="d-flex flex-row justify-content-between align-items-center">
            <div class="d-flex flex-column">
              <h2 class="text-dark mb-0">Expenses</h2>
              <p class="text-light mt-0">Daily overview</p>
            </div>
            <h4 class="text-primary">$<span id="total-expenses" data-total=<%= @totalExpenses.round(2) %>><%= @totalExpenses.round(2) %></span></h4>
          </div>
          <div class="d-flex flex-row justify-content-between align-items-center mt-3">
            <% @categories.each do |category| %>
            <div class="position-relative image__container d-flex justify-content-center align-items-center" data-title="<%= category.title %>">
              <svg class="radial-progress position-absolute" data-percentage="50" data-title="<%= category.title %>" viewBox="0 0 80 80">
                <circle class="incomplete" cx="40" cy="40" r="35" data-title="<%= category.title %>"></circle>
                <circle class="complete" cx="40" cy="40" r="35" data-title="<%= category.title %>"></circle>
              </svg>
              <%= image_tag(category.image, class: 'overview__image', :data => { :title => category.title }) %>
              </div>
            <% end %>
          </div>
        </div>

        <div class="d-none d-lg-block bg-secondary py-5 px-5 mt-5 rounded">
          <h2 class="text-dark mb-0">New Expenses?</h2>
          <p class="text-light mt-0">Here you can add a new expense</p>
          <button type="button" class="btn btn-primary text-secondary py-2 px-4 btn-hover"><%= link_to 'Add', new_expense_path, class:"text-secondary"%></button>
        </div>

    </div> 

    <div class="col-12 col-lg-5 offset-0 offset-lg-1 mt-5 mt-lg-0 mb-5 pb-5">
      <% @expenses.each do |expense| %>
        <%= link_to edit_expense_path(expense), class:"d-block bg-secondary py-4 px-4 rounded mb-3 btn-hover expense", :data => { :title => expense.category.title, :expense => expense.amount.round(2) } do %>
          <div class="d-flex justify-content-between align-items-center">
            <div class="d-flex justify-content-start align-items-center">
              <%= image_tag(expense.category.image, size: 40) %>
              <div class="d-flex flex-column align-items-start justify-content-center mx-3">
                <h3 class="text-dark mb-0"><%= expense.title%></h3>
                <p class="text-light mb-0"><%= expense.category.title%></p>
              </div>
            </div>
            <h2 class="text-primary my-0 mx-2">$<%= expense.amount.round(2) %></h2>
          </div>
        <% end %>
      <% end %>
    </div>

  </div>
</div>

<div class="d-block d-lg-none">   
  <div class="category__btn-container bg-info d-flex justify-content-center align-items-center">
    <%=link_to new_expense_path, class: 'category__btn-fixed' do%>
      <%= image_tag("cross.png", class:"category__btn-add") %>
    <% end %>
  </div>
</div>

<%= javascript_tag do %>
  // Variables
  var $categories = document.querySelectorAll('.image__container')
  var $expenses = document.querySelectorAll('.expense')
  var lastCategoryClicked = null

  // Listener onclick
  $categories.forEach(category => {
    category.addEventListener('click', (e) => {
      var categoryTitle = e.srcElement.getAttribute('data-title')

      checkExpense(categoryTitle)
    })
  })

  // Function to check related expense
  var checkExpense = (categoryTitle) => {
    // Check to display all or just the category
    var showAllCategory = false
    if(lastCategoryClicked == categoryTitle) {
      showAllCategory = true
      lastCategoryClicked = null // To permit a new change with this category
    } else {
      showAllCategory = false
      lastCategoryClicked = categoryTitle
    }

    // Display expense
    $expenses.forEach(expense => {
      var expenseCategoryTitle = expense.getAttribute('data-title')

      // Check to display all or just the category
      if(showAllCategory) {
        expense.setAttribute('style', 'display: block !important')
      } else {
        if(expenseCategoryTitle == categoryTitle) {
          expense.setAttribute('style', 'display: block !important')
          addExpenses(parseFloat(expense.getAttribute('data-expense')))
        } else {
          expense.setAttribute('style', 'display: none !important')
        }
      }
    })

    if(showAllCategory) {
      showExpenses(totalExpenses)
    } else {
      showExpenses(calcExpenses)
    }
  }


  // Get all moneys
  var $totalExpensesContainer = document.querySelector('#total-expenses')
  var totalExpenses = $totalExpensesContainer.getAttribute('data-total')
  var calcExpenses = 0

  // Function to add expenses
  var addExpenses = (expense) => {
    calcExpenses += expense
  }

  // Function to show expenses
  var showExpenses = (expenses) => {
    $totalExpensesContainer.innerHTML = expenses

    calcExpenses = 0
  }


  // Set data money to each category for circle percentage
  var $radialProgress = document.querySelectorAll('.radial-progress')
  var calcCategoryExpenses = 0

  // Function to add expenses
  var addCategoryExpenses = (expense) => {
    calcCategoryExpenses += expense
  }

  // Calc expense for each category
  $radialProgress.forEach($radial => {
    var actualCategory = $radial.getAttribute('data-title')
    var $expenses = document.querySelectorAll(`.expense[data-title="${actualCategory}"]`)

    // Get all expense related to the category
    $expenses.forEach($expense => {
      var actualExpense = $expense.getAttribute('data-expense')
      addCategoryExpenses(parseFloat(actualExpense))
    })

    // Set the actual percentage
    var expensePercent = calcCategoryExpenses / totalExpenses * 100
    $radial.setAttribute("data-percentage", expensePercent)

    calcCategoryExpenses = 0
  })


  // Circle animation
  $radialProgress.forEach($radial => {
    var percent = $radial.getAttribute('data-percentage')
    var radius = $radial.querySelector('circle.complete').getAttribute('r')
    var circumference = 2 * Math.PI * radius
    var strokeDashOffset = circumference - ((percent * circumference) / 100)

    $radial.querySelector('circle.complete').style.strokeDashoffset = strokeDashOffset
  })
<% end %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @category.image %>
</p>

<p>
  <strong>Title:</strong>
  <%= @category.title %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>
<%= link_to 'Delete', @category, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/expenses/_form.html.erb
<%= simple_form_for(@expense) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs mx-lg-5">
    <%= f.input :title, as: :string, label: "Title", placeholder: 'Bubble Tea 🧋', required: true, error: 'Please, enter a title.', autofocus: true, label_html: { class: 'text-primary mt-4 mb-2' }, :input_html => { class: 'input-form text-dark' }, wrapper_html: { class: 'mx-lg-5' }  %>
    <%= f.association :category, as: :select, label: "Category", prompt: 'Select your category...', required: true, error: 'Please, select a valid category.', label_html: { class: 'text-primary mt-4 mb-2' }, :input_html => { class: 'input-form text-dark' }, wrapper_html: { class: 'mx-lg-5' } %>
    <%= f.input :amount, label: "Amount", placeholder: '6,50', required: true, error: 'Please, enter a valid amount.', label_html: { class: 'text-primary mt-4 mb-2' }, :input_html => { class: 'input-form text-dark', value: number_with_precision(f.object.amount, precision: 2) }, wrapper_html: { class: 'mx-lg-5' } %>
    <%= f.input :date, as: :date, label: "Date", required: true, error: 'Please, enter a valid date.', label_html: { class: 'text-primary mt-4 mb-2' }, :input_html => { class: 'input-form text-dark' }, wrapper_html: { class: 'mx-lg-5' } %>
  </div>

  <div class="form-actions d-flex justify-content-center align-items-center mt-5">
    <% if request.path != '/expenses/new' && request.path != '/expenses' %>
      <button type="button" class="btn btn-danger py-2 px-4 mx-2 mx-lg-5 btn-hover"><%= link_to 'Delete', @expense, method: :delete, data: { confirm: 'Are you sure?' }, class:"text-secondary" %></button>
    <% end %>
    <%= f.button :submit, '  Save  ', class:"text-secondary btn btn-primary py-2 px-4 mx-2 mx-lg-5 font-size btn-hover" %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<%= render 'header',
            image: @expense.category.image,
            small: "Your",
            large: "Expense!" %>

<div class="container">
    <div class="col-8 offset-2">
        <div class="row bg-secondary px-5 py-5 rounded">
            <%= render 'form', expense: @expense %>
        </div>
    </div>
</div>

app/views/expenses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Expenses</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Category</th>
      <th>Amount</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @expenses.each do |expense| %>
      <tr>
        <td><%= expense.title %></td>
        <td><%= expense.category %></td>
        <td><%= expense.amount %></td>
        <td><%= expense.date %></td>
        <td><%= link_to 'Show', expense %></td>
        <td><%= link_to 'Edit', edit_expense_path(expense) %></td>
        <td><%= link_to 'Destroy', expense, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Expense', new_expense_path %>

app/views/expenses/new.html.erb
<%= render 'header',
            image: 'money-mouth-face.png',
            small: "Enter your ",
            large: "Expense!" %>

<%# <h1>New Expense</h1> %>

<div class="container">
    <div class="col-8 offset-2">
        <div class="row bg-secondary px-5 py-5 rounded">
            <div>
                <%= render 'form', expense: @expense %>
            </div>
        </div>
    </div>
</div>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @expense.title %>
</p>

<p>
  <strong>Category:</strong>
  <%= @expense.category %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @expense.amount %>
</p>

<p>
  <strong>Date:</strong>
  <%= @expense.date %>
</p>

<%= link_to 'Edit', edit_expense_path(@expense) %> |
<%= link_to 'Back', expenses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Lemon Debt</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body class="bg-info">
    <%= yield %>
  </body>
</html>